name: sub_parser

on:
  workflow_dispatch:
  push:
    paths:
      - 'sub_parser.py'
      - '.github/workflows/sub_parser.yml'
  schedule:
    - cron: '0 16 * * *'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Local Repo
        uses: actions/checkout@v4

      - name: Checkout Private Repo (Config Only)
        uses: actions/checkout@v4
        with:
          repository: qjlxg/362
          token: ${{ secrets.GH_TOKEN }}
          path: private_folder

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Deps
        run: pip install requests maxminddb PyYAML

      - name: Execute
        env:
          TZ: Asia/Shanghai
          DATA_PATH: private_folder/data
          
          LINK: ${{ secrets.LINK }}
        run: python sub_parser.py

      - name: Push to Local Repo
        run: |
          git config --local user.email "bot@github.com"
          git config --local user.name "NodeParserBot"
          git add data/

          git diff --quiet && git diff --staged --quiet || (git commit -m "Update nodes: $(date +'%Y-%m-%d %H:%M')" && git push)
